server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: toor
  # thymeleaf
  thymeleaf:
    cache: false

  # email
  mail:
    host: smtp.163.com
    username: byojiaoxianz7@163.com
    password: CWZOYWRFPKLOZKHK
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # redis
  redis:
    database: 11
    host: localhost
    port: 6379

mybatis:
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 自动生成 id
    use-generated-keys: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.community.entity

# community
community:
  path:
    domain: http://localhost:8080


# aliyun OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI4GAK8Ei4gy9MTqMHohyP
      keysecret: 4t859qr4Vy6HmkXDvjbGLUy7SiVbmc
      # bucket可以在控制台创建，也可以使用 java 代码创建
      bucketname: weizujie

